#version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

issues:
  exclude-dirs:
    - api/proto
    - scripts
  exclude-rules:
    - path: internal/telemetry/
      linters:
        - contextcheck
    - path: cmd/seed/
      linters:
        - tagliatelle
        - mnd
        - gosec
        - gocritic
    - path: examples/transformers/
      linters:
        - tagliatelle
        - mnd
        - gocritic
        - dupl

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - contextcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - mnd
    - gosec
    - makezero
    - misspell
    - nilerr
    - noctx
    - revive
    - tagliatelle
    - usetesting
    - unconvert
    - unparam
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - nakedret
    - prealloc
    - stylecheck
    - whitespace
  disable:
    - gochecknoinits
    - gochecknoglobals
    - wrapcheck

linters-settings:
  mnd:
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "10"
    ignored-functions:
      - "make"
      - "os.Exit"
      - "strconv.*"
      - "time.Duration"
      - "context.WithTimeout"
      - "slog.NewRecord"
    ignored-files:
      - "_test.go"
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  exhaustive:
    default-signifies-exhaustive: true
  tagliatelle:
    case:
      rules:
        yaml: snake
        json: goCamel
