// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: v1/health.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{0}
}

type HealthCheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReply) Reset() {
	*x = HealthCheckReply{}
	mi := &file_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReply) ProtoMessage() {}

func (x *HealthCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReply.ProtoReflect.Descriptor instead.
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_v1_health_proto protoreflect.FileDescriptor

const file_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/health.proto\x12\tquanta.v1\"\x14\n" +
	"\x12HealthCheckRequest\"\"\n" +
	"\x10HealthCheckReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2M\n" +
	"\x06Health\x12C\n" +
	"\x05Check\x12\x1d.quanta.v1.HealthCheckRequest\x1a\x1b.quanta.v1.HealthCheckReplyB\x18Z\x16quanta/api/proto/v1;pbb\x06proto3"

var (
	file_v1_health_proto_rawDescOnce sync.Once
	file_v1_health_proto_rawDescData []byte
)

func file_v1_health_proto_rawDescGZIP() []byte {
	file_v1_health_proto_rawDescOnce.Do(func() {
		file_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_health_proto_rawDesc), len(file_v1_health_proto_rawDesc)))
	})
	return file_v1_health_proto_rawDescData
}

var file_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil), // 0: quanta.v1.HealthCheckRequest
	(*HealthCheckReply)(nil),   // 1: quanta.v1.HealthCheckReply
}
var file_v1_health_proto_depIdxs = []int32{
	0, // 0: quanta.v1.Health.Check:input_type -> quanta.v1.HealthCheckRequest
	1, // 1: quanta.v1.Health.Check:output_type -> quanta.v1.HealthCheckReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_health_proto_init() }
func file_v1_health_proto_init() {
	if File_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_health_proto_rawDesc), len(file_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_health_proto_goTypes,
		DependencyIndexes: file_v1_health_proto_depIdxs,
		MessageInfos:      file_v1_health_proto_msgTypes,
	}.Build()
	File_v1_health_proto = out.File
	file_v1_health_proto_goTypes = nil
	file_v1_health_proto_depIdxs = nil
}
